### ISSUE TITLE
Events forEach problem

### ISSUE THREAD

**Issue by calebebrim** [Brightspace/serverless-plugin-for-each#32]
![image](https://user-images.githubusercontent.com/3729216/204922118-540e8eb2-24ac-4644-a7c8-dd4e6f45754b.png)

![image](https://user-images.githubusercontent.com/3729216/204922182-ddea2f23-7823-4c1f-9358-488075c47fa5.png)

I've tryed also with the commented line and it does not work.

frameworkVersion: '3'

**Comment by AntonBazhal** [comment]
What is `- msk`? Shouldn't it be `- kafka`?

**Comment by calebebrim** [comment]
Just for reference: 
https://www.serverless.com/framework/docs/providers/aws/guide/serverless.yml/#msk

**Comment by calebebrim** [comment]
I'm trying this:

```
msk_event:
  handler: src/handler.msk_event_handler
  environment: ${file(envs/env.${sls:stage}.yml)}
  timeout: 29
  layers:
    - { Ref: PythonRequirementsLambdaLayer }
  package:
    patterns:
      - "!./**"
      - "src/**/*.py"     
  events:
    - $forEach: 
        iterator: $split(${file(./envs/env.${sls:stage, 'dev'}.yml):topicsNames}, ',')}
        # iterator: ${ops:custom.topicsNames}
        template:
          - msk:
            arn: "${file(envs/env.${opt:stage, 'dev'}.yml):KAFKA_CLUSTER_ARN}"
            topic: $forEach.value
            batchSize: 10
            maximumBatchingWindow: 10
            startingPosition: LATEST
```

**Comment by AntonBazhal** [comment]
Now template indentation seems not correct
```yaml
msk_event:
  handler: src/handler.msk_event_handler
  environment: ${file(envs/env.${sls:stage}.yml)}
  timeout: 29
  layers:
    - { Ref: PythonRequirementsLambdaLayer }
  package:
    patterns:
      - "!./**"
      - "src/**/*.py"     
  events:
    - $forEach: 
        iterator: $split(${file(./envs/env.${sls:stage, 'dev'}.yml):topicsNames}, ',')}
        template:
          - msk:
              arn: "${file(envs/env.${opt:stage, 'dev'}.yml):KAFKA_CLUSTER_ARN}"
              topic: $forEach.value
              batchSize: 10
              maximumBatchingWindow: 10
              startingPosition: LATEST
```

**Comment by calebebrim** [comment]
```yaml
msk_event:
  handler: src/handler.msk_event_handler
  environment: ${file(envs/env.${sls:stage}.yml)}
  timeout: 29
  layers:
    - { Ref: PythonRequirementsLambdaLayer }
  package:
    patterns:
      - "!./**"
      - "src/**/*.py"     
  events:
    - $forEach: 
        iterator: $split(${file(./envs/env.${sls:stage, 'dev'}.yml):topicNames}, ',')}
        template:
          - msk:
              arn: "${file(envs/env.${opt:stage, 'dev'}.yml):KAFKA_CLUSTER_ARN}"
              topic: $forEach.value
              batchSize: 10
              maximumBatchingWindow: 10
              startingPosition: LATEST
````

Still: 

![image](https://user-images.githubusercontent.com/3729216/205055314-2163b0a4-8192-44a6-9efd-265d5fd7d0c4.png)
