### ISSUE TITLE
ForEach in forEach

### ISSUE THREAD

**Issue by throrin19** [Brightspace/serverless-plugin-for-each#61]
Hello, Is it possible to made a `$forEach` inside another `$forEach` ? 

In my case I have this configuration in my custom part : 

```yml
custom
  foo:
    # Content of barOne and barTwo are retrived from ssm/secret-manager
    # barOne: ${ssm:/aws/reference/secretsmanager/bar-one}
    # barTwo: ${ssm:/aws/reference/secretsmanager/bar-two}
    barOne:
        DB_PASSWORD_BAR_ONE: value
        DB_HOST_BAR_ONE: value
    barTwo:
        DB_PASSWORD_BAR_TWO: value
        DB_HOST_BAR_TWO: value
```

And I want made this in `provider.environment` : 

```yml
provider:
  environment:
    DB_PASSWORD_BAR_ONE: value
    DB_HOST_BAR_ONE: value
    DB_PASSWORD_BAR_TWO: value
    DB_HOST_BAR_TWO: value
```

I've try this with $forEach plugin : 

```yml
provider:
  environment:
    $forEach:
      iterator: ${self:custom.foo}
      template:
        $forEach:
          iterator: $forEach.value
          template:
            $forEach.key: $forEach.value
```

But I have this error : 

```
Error: provider.environment.$forEach.template/$forEach/iterator must be array, provider.environment.$forEach.template/$forEach/iterator must be object, provider.environment.$forEach.template/$forEach/iterator must match exactly one schema in oneOf
```

**Comment by AntonBazhal** [comment]
I don't think this is currently possible. Nesting `$forEach` is supported, but the plugin does a depth-first traversal to avoid ambiguity.

**Comment by throrin19** [comment]
There is no solution to made this, or an example for nesting `$forEach` ?

**Comment by throrin19** [comment]
I try to remove ambiguity with `$forEach_named` but the problem is the same. This plugin does not respond to this use case....

**Comment by AntonBazhal** [comment]
As I mentioned above, the plugin supports nesting, but it interpolates nested `$forEach` before the parent one. There are [two tests](https://github.com/Brightspace/serverless-plugin-for-each/blob/d0b3e8b67f5fc68551656173791c65885442e71b/test/index.spec.js#L347) that show how this works for objects and arrays.

**Comment by throrin19** [comment]
I resolve my problem using `@cruglobal/serverless-merge-config` with this plugin : 

```yml
custom
  foo:
    $<<:
      - DB_PASSWORD_BAR_ONE: value
        DB_HOST_BAR_ONE: value
      - DB_PASSWORD_BAR_TWO: value
        DB_HOST_BAR_TWO: value

provider:
  environment:
    $forEach:
      iterator: ${self:custom.foo}
      template:
        $forEach.key: $forEach.value

plugins:
  - '@cruglobal/serverless-merge-config'
  - serverless-plugin-for-each
```
