### ISSUE TITLE
No escape in interpolate value

### ISSUE THREAD

**Issue by throrin19** [Brightspace/serverless-plugin-for-each#62]
Hello, 

I have a problem with forEach in a case the string contains special chars for JSON (like `"`).

If we try to use the `$forEach` with one of this value, we have the error `Interpolated template is not a valid JSON` : 

Example : 

```yml
$forEach:
  iterator: 
    - test: '{"example": "example"}
  template:
    $forEach.key: $forEach.value
```

to avoid that, I think we should make a `JSON.stringify` on the `value` part of interpolated
