### ISSUE TITLE
Foreach.value inside $file issue

### ISSUE THREAD

**Issue by cachila** [Brightspace/serverless-plugin-for-each#65]
Hello, I'm having an issue with using forEach.value inside a $file. This error pops-up

```
Cannot resolve serverless.yml: Variables resolution errored with:
  - Variable syntax error at "stepFunctions.stateMachines.$forEach_stepFunctions.template.$forEach.key.definition": Invalid variable type at index 35 in "${file(step-function-definitions/${forEach.value})}"
```

```
    $forEach_stepFunctions:
      iterator: 
        ${self:custom.stepFunctionIterator}
      template:
        $forEach.key:
          name: $forEach.key
          definition: ${file(step-function-definitions/${forEach.value})}
```

Any idea how to fix this?

Thanks!
