### ISSUE TITLE
ForEach not working in custom serverless section

### ISSUE THREAD

**Issue by mmiara** [Brightspace/serverless-plugin-for-each#71]
I am trying to use this to loop through a list of domains to be used with `serverless-domain-manager`. Below is the code I am attempting to use:
```
customDomains:
    enabled: ${self:custom.${self:provider.stage}}
    stage: ${opt:stage, self:provider.stage}
    certificateName: testcert1
    createRoute53Record: false
    $forEach:
      iterator:
        domain1: example1.com
      template:
        - http:
            domainName: $forEach.value
            basePath: ${self:custom.internalPath}
            endpointType: regional
```
but I am getting the below error:
```
$ sls package -r $AWS_REGION --package output/
(node:70) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.
Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
(node:70) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.
Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
Packaging serverless-test for stage dev (us-east-1)
Environment: linux, node 20.5.0, framework 3.27.0, plugin 6.2.3, SDK 4.3.2
Credentials: Local, environment variables
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues
Error:
Error: Can't merge array into object
    at ForEachPlugin.findAndReplace (/usr/local/lib/node_modules/serverless-plugin-for-each/src/index.js:132:13)
    at ForEachPlugin.findAndReplace (/usr/local/lib/node_modules/serverless-plugin-for-each/src/index.js:98:19)
    at /usr/local/lib/node_modules/serverless-plugin-for-each/src/index.js:165:17
    at Array.reduce (<anonymous>)
    at ForEachPlugin.replace (/usr/local/lib/node_modules/serverless-plugin-for-each/src/index.js:163:57)
    at PluginManager.runHooks (/usr/local/lib/node_modules/serverless/lib/classes/plugin-manager.js:[53](https://gitlab.com/pipelines/serverless/deployment/-/jobs/7253456#L53)0:15)
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/plugin-manager.js:[56](https://gitlab.com/pipelines/serverless/deployment/-/jobs/725032456#L56)5:20)
    at async PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/plugin-manager.js:[60](https://gitlab.com/pipelines/serverless/deployment/-/jobs/72502356#L60)4:7)
    at async Serverless.run (/usr/local/lib/node_modules/serverless/lib/serverless.js:179:5)
    at async /usr/local/lib/node_modules/serverless/scripts/serverless.js:812:9
1 deprecation found: run 'serverless doctor' for more details
```
I have attempted to use different variations of the iterator, but this seems to be the most simple one, as the iterator it being hard-coded into the forEach section. Is there something I am missing where I am unable to use this within the custom section?

Thanks!
